# Generated by Django 4.2.29 on 2026-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('runame', models.CharField(max_length=500)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
