# Generated by Django 4.2.29 on 2026-03-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='discription',
            new_name='description',
        ),
    ]
