# Generated by Django 4.2.29 on 2026-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_discription_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='main_track_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.FloatField()),
                ('genre_id', models.FloatField()),
            ],
        ),
    ]
