# Generated by Django 4.2.29 on 2026-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_track',
        ),
        migrations.DeleteModel(
            name='main_track_genres',
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(to='main.genre'),
        ),
    ]
